version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.14
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 1000
    ports:
      - "22181:2181"

  broker:
    image: confluentinc/cp-kafka:6.0.14
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  redis:
    image: redis:7.0.11
    container_name: redis
    ports:
      - "6379:6379"

  rba-producer:
    image: rba-producer:1.0.0
    build: ./rba-producer
    container_name: rba-producer
    depends_on:
      - zookeeper
      - broker

  rba-rest:
    image: rba-rest:1.0.0
    build: ./rba-rest
    container_name: rba-rest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - zookeeper
      - broker
